DROP TABLE IF EXISTS projecteVota;

CREATE TABLE projecteVota;
USE projecteVota;

DROP TABLE IF EXISTS 'votants';

CREATE TABLE 'votants'{
	'ID' INT(3) NOT NULL AUTO_INCREMENT,
	'NOM' VARCHAR2(20) NOT NULL DEFAULT '',
	'EMAIL' VARCHAR2(40) NOT NULL DEFAULT '',
	'PASSWORD' INT(20) NOT NULL DEFAULT '',
	PRIMARY KEY(ID);
}

DROP TABLE IF EXISTS 'admins';

CREATE TABLE 'admins'{
	'ID' INT(3) NOT NULL AUTO_INCREMENT,
	'NOM' VARCHAR2(20) NOT NULL DEFAULT '',
	'EMAIL' VARCHAR2(40) NOT NULL DEFAULT '',
	'PASSWORD' INT(20) NOT NULL DEFAULT '',
	'ADMIN' BOOLEAN('TRUE'),
	PRIMARY KEY(ID);
}

DROP TABLE IF EXISTS 'consulta';

CREATE TABLE 'consulta'

